import { h } from 'preact';
declare const _default: {
    parameters: {
        fixedWidth: boolean;
    };
    title: string;
};
export default _default;
export declare const AlignBottom: () => h.JSX.Element;
export declare const AlignMiddle: () => h.JSX.Element;
export declare const AlignTop: () => h.JSX.Element;
export declare const AnchorHorizontal: () => h.JSX.Element;
export declare const AnchorVertical: () => h.JSX.Element;
export declare const ArrowDown: () => h.JSX.Element;
export declare const ArrowLeftRight: () => h.JSX.Element;
export declare const ArrowLeft: () => h.JSX.Element;
export declare const ArrowRight: () => h.JSX.Element;
export declare const ArrowUpDown: () => h.JSX.Element;
export declare const ArrowUp: () => h.JSX.Element;
export declare const AutoLayoutHorizontalBottom: () => h.JSX.Element;
export declare const AutoLayoutHorizontalCenter: () => h.JSX.Element;
export declare const AutoLayoutHorizontalTop: () => h.JSX.Element;
export declare const AutoLayoutVerticalCenter: () => h.JSX.Element;
export declare const AutoLayoutVerticalLeft: () => h.JSX.Element;
export declare const AutoLayoutVerticalRight: () => h.JSX.Element;
export declare const CaretDown: () => h.JSX.Element;
export declare const CaretLeft: () => h.JSX.Element;
export declare const CaretRight: () => h.JSX.Element;
export declare const CaretUp: () => h.JSX.Element;
export declare const ChevronDown: () => h.JSX.Element;
export declare const ChevronUp: () => h.JSX.Element;
export declare const CircleHelp: () => h.JSX.Element;
export declare const CircleInfo: () => h.JSX.Element;
export declare const Code: () => h.JSX.Element;
export declare const Connector: () => h.JSX.Element;
export declare const Hyperlink: () => h.JSX.Element;
export declare const LayerAnimated: () => h.JSX.Element;
export declare const LayerComponent: () => h.JSX.Element;
export declare const LayerEllipse: () => h.JSX.Element;
export declare const LayerFrameCoverArt: () => h.JSX.Element;
export declare const LayerFrameScrollingHorizontal: () => h.JSX.Element;
export declare const LayerFrameScrollingVertical: () => h.JSX.Element;
export declare const LayerFrameScrolling: () => h.JSX.Element;
export declare const LayerFrame: () => h.JSX.Element;
export declare const LayerGroup: () => h.JSX.Element;
export declare const LayerImage: () => h.JSX.Element;
export declare const LayerInstance: () => h.JSX.Element;
export declare const LayerLine: () => h.JSX.Element;
export declare const LayerMask: () => h.JSX.Element;
export declare const LayerRectangle: () => h.JSX.Element;
export declare const LayerSlice: () => h.JSX.Element;
export declare const LayerText: () => h.JSX.Element;
export declare const LayerVector: () => h.JSX.Element;
export declare const LockLocked: () => h.JSX.Element;
export declare const LockUnlocked: () => h.JSX.Element;
export declare const MenuCheckmarkBreadcrumb: () => h.JSX.Element;
export declare const MenuCheckmarkChecked: () => h.JSX.Element;
export declare const MenuCheckmarkMixed: () => h.JSX.Element;
export declare const MoveDown: () => h.JSX.Element;
export declare const MoveRight: () => h.JSX.Element;
export declare const OptionCheck: () => h.JSX.Element;
export declare const OptionDisabled: () => h.JSX.Element;
export declare const OrientationLandscape: () => h.JSX.Element;
export declare const OrientationPortrait: () => h.JSX.Element;
export declare const PaddingHorizontal: () => h.JSX.Element;
export declare const PaddingVertical: () => h.JSX.Element;
export declare const SpaceHorizontal: () => h.JSX.Element;
export declare const SpaceVertical: () => h.JSX.Element;
export declare const StarFilled: () => h.JSX.Element;
export declare const Star: () => h.JSX.Element;
export declare const Swap: () => h.JSX.Element;
export declare const Target: () => h.JSX.Element;
export declare const TextAlignCenter: () => h.JSX.Element;
export declare const TextAlignJustified: () => h.JSX.Element;
export declare const TextAlignLeft: () => h.JSX.Element;
export declare const TextAlignRight: () => h.JSX.Element;
export declare const TextDecorationStrikethrough: () => h.JSX.Element;
export declare const TextDecorationUnderline: () => h.JSX.Element;
export declare const Upload: () => h.JSX.Element;
export declare const VisibilityHidden: () => h.JSX.Element;
export declare const VisibilityVisible: () => h.JSX.Element;
export declare const Warning: () => h.JSX.Element;
export declare const World: () => h.JSX.Element;
//# sourceMappingURL=icon-16.stories.d.ts.map