declare const styles: {
  readonly "component": string;
  readonly "components": string;
  readonly "create-figma-plugin": string;
  readonly "documents": string;
  readonly "drop-mod-menu": string;
  readonly "drop-mod-target": string;
  readonly "drop-mod-target-unsaved": string;
  readonly "editor": string;
  readonly "fp-TabsContent": string;
  readonly "highlight": string;
  readonly "icon": string;
  readonly "list": string;
  readonly "props-select": string;
  readonly "search-mode": string;
  readonly "status-actions": string;
  readonly "status-bar": string;
  readonly "tab": string;
  readonly "tab-bar": string;
  readonly "tab-bar-nav": string;
  readonly "tab-btn": string;
  readonly "tab-menu": string;
  readonly "tab-view": string;
  readonly "tabs": string;
  readonly "theme-picker-colors": string;
  readonly "theme-picker-palette": string;
  readonly "tip": string;
  readonly "virtuoso-grid-list": string;
};
export = styles;

