import { Animated } from 'react-native';
import { MotionPressable } from './MotionPressable';
export declare namespace Motion {
    const View: <TAnimate, TAnimateProps>(p: Animated.AnimatedProps<import("react-native").ViewProps & import("react").RefAttributes<import("react-native").View>> & import("./Interfaces").MotionComponentProps<typeof import("react-native").View, import("react-native").ViewStyle, TAnimate, TAnimateProps, unknown>, ref: import("react").Ref<import("react-native").View>) => import("react").ReactElement;
    const Text: <TAnimate, TAnimateProps>(p: Animated.AnimatedProps<import("react-native").TextProps & import("react").RefAttributes<import("react-native").Text>> & import("./Interfaces").MotionComponentProps<typeof import("react-native").Text, import("react-native").TextStyle, TAnimate, TAnimateProps, unknown>, ref: import("react").Ref<import("react-native").Text>) => import("react").ReactElement;
    const FlatList: <TAnimate, TAnimateProps>(p: Animated.AnimatedProps<Animated.AnimatedProps<import("react-native").FlatListProps<unknown>> & import("react").RefAttributes<Animated.FlatList<unknown>>> & import("./Interfaces").MotionComponentProps<typeof Animated.FlatList, Animated.Value | Animated.AnimatedInterpolation | Animated.WithAnimatedObject<import("react-native").ViewStyle>, TAnimate, TAnimateProps, unknown>, ref: import("react").Ref<Animated.FlatList<unknown>>) => import("react").ReactElement;
    const Image: <TAnimate, TAnimateProps>(p: Animated.AnimatedProps<import("react-native").ImageProps & import("react").RefAttributes<import("react-native").Image>> & import("./Interfaces").MotionComponentProps<typeof import("react-native").Image, import("react-native").ImageStyle, TAnimate, TAnimateProps, unknown>, ref: import("react").Ref<import("react-native").Image>) => import("react").ReactElement;
    const ScrollView: <TAnimate, TAnimateProps>(p: Animated.AnimatedProps<import("react-native").ScrollViewProps & import("react").RefAttributes<import("react-native").ScrollView>> & import("./Interfaces").MotionComponentProps<typeof import("react-native").ScrollView, import("react-native").ViewStyle, TAnimate, TAnimateProps, unknown>, ref: import("react").Ref<import("react-native").ScrollView>) => import("react").ReactElement;
    const SectionList: <TAnimate, TAnimateProps>(p: Animated.AnimatedProps<Animated.AnimatedProps<import("react-native").SectionListProps<unknown, unknown>> & import("react").RefAttributes<Animated.SectionList<unknown, unknown>>> & import("./Interfaces").MotionComponentProps<typeof Animated.SectionList, Animated.Value | Animated.AnimatedInterpolation | Animated.WithAnimatedObject<import("react-native").ViewStyle>, TAnimate, TAnimateProps, unknown>, ref: import("react").Ref<Animated.SectionList<unknown, unknown>>) => import("react").ReactElement;
    const Pressable: typeof MotionPressable;
}
