export const F2RN_CONFIG_NS = 'f2rn:config:v1';
export const F2RN_PROJECT_NS = 'f2rn:project:v1';
export const F2RN_NAVIGATE_NS = 'f2rn:navigate:v1';
export const F2RN_STYLEGEN_API = 'https://f2rn.deno.dev';

export const SUPABASE_PROJECT_URL = 'http://localhost:54321'; // 'https://ndfwacmspvrwdiqqeecz.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0'; // 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kZndhY21zcHZyd2RpcXFlZWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTUyODA0MDYsImV4cCI6MjAxMDg1NjQwNn0.1ZfkWFCp20pYVU0d9ggmaIe36lFbZFYmOP_bXgtrHxI';

export const TIPTAP_APP_ID = '0x9lnvmr';

export const LOGTAIL_TOKEN = '3hRzjtVJTBk6BDFt3pSjjKam';

export const GPT4_VISION_PROMPT = `You are a professional React Native developer.

Correct the provided code for this React Native component using the provided image generated by Figma as a reference.

Only return the corrected component code.`;

export const UNISTYLES_LIB = `import {createUnistyles} from 'react-native-unistyles';
import theme, {breakpoints} from 'theme';

export const {createStyleSheet, useStyles} = createUnistyles<
  typeof breakpoints,
  typeof theme
>(breakpoints);
`;
